sudo: false
language: ruby
cache: bundler

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.2
  - jruby-9.1.12.0

services:
  - mongodb
  - redis-server

addons:
  rethinkdb: '2.3.6'

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_mongoid_5.gemfile
  - gemfiles/rails_4.2_nobrainer.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.0_nobrainer.gemfile

before_script:
  - mkdir /tmp/dynamodb
  - wget -O - https://s3-ap-southeast-1.amazonaws.com/dynamodb-local-singapore/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory -delayTransientStatuses -port 30180 &
  - mongod --version

script:
  - bundle exec rspec spec
  - bundle exec rake test

matrix:
  exclude:
    - rvm: 2.2.6
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_4.2_nobrainer.gemfile
    - rvm: jruby-9.1.12.0
      gemfile: gemfiles/rails_5.0_nobrainer.gemfile

notifications:
  slack:
    secure: gpltVWntdKz0nSE6A5UvuX4qbN35uW51nsW+Ojgqm8Qsv8K240/NlZRYutFHr7GnJTe0rEEP2Oy3ZBnBtZKFn13RlTEAU/FCAxebr4H24rr29Ypwwp5xjiSE4MuoBEnroo4lw6ka3LsJnrY2PKRMiLJGsS0WsEPY4x8NUG/vyY8=
