sudo: false
language: ruby
cache: bundler

rvm:
  # - 1.8.7
  # - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  # - jruby-18mode # JRuby in 1.8 mode
  - jruby-1.7 # JRuby in 1.9 mode
  - rbx-2.2.1

services: mongodb

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.0_bson1.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.1_bson1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_bson1.gemfile

matrix:
  allow_failures:
    - rvm: rbx-2.2.1
    - rvm: jruby-1.7
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.1.gemfile
