sudo: false
language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-1.7 # JRuby in 1.9 mode
  - jruby-9.0.4.0
  - rbx-2.5.8

services:
  - mongodb
  - redis-server

gemfile:
  - gemfiles/rails_3.2_stable.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.0_mongo_mapper.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.1_mongo_mapper.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_mongoid_5.gemfile
  - gemfiles/rails_4.2_mongo_mapper.gemfile
  - gemfiles/rails_5.0.gemfile

before_script:
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory -delayTransientStatuses -port 30180 &

matrix:
  allow_failures:
    - rvm: rbx-2.2.1
    - rvm: jruby-1.7
    - rvm: 2.3
    - gemfile: gemfiles/rails_5.0.gemfile
  exclude:
    - rvm: 1.9.3
      gemfile:
        - gemfiles/rails_4.1.gemfile
        - gemfiles/rails_5.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_3.2_stable.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_3.2_stable.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_4.1.gemfile
